general:
  valveCount: 5
  valvesConcurrency: 2
  latitude: 32.156835
  longitude: 34.805154
  timezone: 'Israel'

mqtt:
  enabled: true
  hostname: localhost
  clientname: irrigationPi

telemetry:
  enabled: true
  idleinterval: 10

schedules:
  # type: absolute, sunrise, sunset
  # start:
  #   When type is 'absolute' start denotes exact time. When type is 'sunrise' or 
  #   'sunset' start denotes offset from sunrise / sunset. +00:10 means 10 minutes 
  #   after, -00:15 means 15 minutes before. 
  # duration: in minutes
  sunSummerSched: 
    # All days of the week, for 20 minutes, at 06:10 am
    seasons: [Spring, Summer]
    days: [Sun, Mon, Tue, Wed, Thu, Fri, Sat]
    type: sunrise 
    start: '+00:10'
    duration: 15
    sensor: darkskySensor
  sunWinterSched: 
    # All days of the week, for 20 minutes, at 06:10 am
    seasons: [Fall, Winter]
    days: [Sun, Mon, Tue, Wed, Thu, Fri, Sat]
    type: sunrise 
    start: '+00:10'
    duration: 15
    sensor: darkskySensor
  shadeSched:
    # On Sunday and Thursday, for 15 minutes, 10 minutes after sunrise. 
    seasons: [Spring, Summer, Fall, Winter]
    days: [Mon, Wed, Fri]
    type: sunrise
    start: '+00:10'
    duration: 15
    sensor: darkskySensor
  frontLawnSummerSched: 
    seasons: [Spring, Summer]
    days: [Thu]
    type: absolute 
    start: '08:50'
    duration: 20
    sensor: darkskySensor
  frontLawnWinterSched: 
    seasons: [Fall, Winter]
    days: [Thu]
    type: absolute 
    start: '08:50'
    duration: 20
    sensor: darkskySensor
  backLawnSummerSched: 
    seasons: [Spring, Summer]
    days: [Mon, Thu]
    type: sunrise 
    start: '+00:20'
    duration: 20
    sensor: darkskySensor
  backLawnWinterSched: 
    seasons: [Fall, Winter]
    days: [Mon]
    type: sunrise 
    start: '+00:20'
    duration: 20
    sensor: darkskySensor

valves:
  valve1: 
    enabled: true
    schedules: 
      - backLawnSummerSched
      - backLawnWinterSched
  valve2: 
    enabled: true
    schedules: 
      - frontLawnSummerSched
      - frontLawnWinterSched
  valve3:
    enabled: true
    schedules: 
      - shadeSched
  valve4:
    enabled: true
    schedules: 
      - sunSummerSched
      - sunWinterSched
  valve5:
    enabled: true
    schedules: 
      - sunSummerSched
      - sunWinterSched

sensors:
  darkskySensor:
    enabled: true
    type: darksky
    apikey: <darksky_apikey>
    latitude: 32.156835
    longitude: 34.805154
    probabilityThreshold: 0.0
    updateinterval: 240