general:
  valveCount: 5
  valvesConcurrency: 2
  latitude: 32.132
  longitude: 34.838
  timezone: 'Israel'

mqtt:
  enabled: true
  hostname: dockerpi
  clientname: irrigationPi

schedules:
  # type: absolute, sunrise, sunset
  # start:
  #   When type is 'absolute' start denotes exact time. When type is 'sunrise' or 
  #   'sunset' start denotes offset from sunrise / sunset. +00:10 means 10 minutes 
  #   after, -00:15 means 15 minutes before. 
  # duration: in minutes
  sched1: 
    # All days of the week, for 20 minutes, at 06:10 am
    days: [Sun, Mon, Tue, Wed, Thu, Fri, Sat]
    type: absolute 
    start: '09:10'
    duration: 1
  sched2:
    # On Sunday and Thursday, for 15 minutes, 10 minutes after sunrise. 
    days: [Sun, Mon, Tue, Wed, Thu, Fri, Sat]
    type: absolute 
    start: '09:11'
    duration: 1
  sched3:
    # On Sunday and Thursday, for 15 minutes, 10 minutes after sunrise. 
    days: [Sun, Mon, Tue, Wed, Thu, Fri, Sat]
    type: sunset
    start: '-00:30'
    duration: 15
  sched4:
    days: [Sun, Mon, Tue, Wed, Thu, Fri, Sat]
    type: absolute 
    start: '09:11'
    duration: 1
    sensor: sensor1

valves:
  valve1: 
    enabled: true
    schedules: 
      - sched1
  valve2: 
    enabled: true
    schedules: 
      - sched1
  valve3:
    enabled: true
    schedules: 
      - sched2
  valve4:
    enabled: false
    schedules: 
      - sched3
  valve5:
    enabled: true
    schedules: 
      - sched4

sensors:
  sensor1:
    enabled: true
    type: test
  sensor2:
    enabled: true
    type: uv